[package]
name = "fabriko_derive"
version = "0.1.0"
edition = "2021"
authors = ["Olivier Pinon <oliv.pinon@gmail.com>"]
license = "MIT"

[lib]
proc-macro = true

[dependencies]
darling = "0.20"
fnv = "1.0.7"
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
