[package]
name = "association_one_to_one"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fabriko = { version = "0.1.0", path = "../../fabriko" }
nutype = "0.3.1"
